program_id = "Evm8pTZbiKSiBbNTRCtLVBLZypqmosD8M2Wg2qfoqnA2"

no_update_tracking_owners = [
    "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny",  # Chainlink oracle
    "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ",   # Pyth oracle
    "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s",   # Pyth legacy oracle
]

operators_whitelist = [
    "Eaqbds3i1WQEQWS94bNKjbDiVFPLZ6arWKZjBGdPckp9",
]

[chain.neon]
id = 285022928
token = "NeoZdcprg7VfhSmqjNw4sg4ckDSGsm3avp8J24QHCkP"

[chain.sol]
id = 285022927
token = "So11111111111111111111111111111111111111112"
